app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('create_task/', create_task, name='create_task'),
    path('update_task/<int:pk>/', update_task, name='update_task'),
    path('delete_task/<int:pk>/', delete_task, name='delete_task'),
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=2000)
    date_creation = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

app/forms.py
from dataclasses import fields
from .models import *
from django.forms import ModelForm


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']
        

app/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import *

# Create your views here.
def index(request):

    tasks = Task.objects.all()

    context = {
        'tasks': tasks,
    }

    return render(request, 'index.html', context)

def create_task(request):

    form = TaskForm()

    context = {
        'form': form,
    }

    if request.method == 'POST':
        form = TaskForm(request.POST)

        if form.is_valid():
            form.save()

            return render(request, 'create_task.html', context)

    return render(request, 'create_task.html', context)

def update_task(request, pk):

    task = Task.objects.get(id=pk)
    form = TaskForm(instance=task)

    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)

        if form.is_valid():
            form.save()

            return redirect('index')

    context = {
        'task': task,
        'form': form,
    }

    return render(request, 'update_task.html', context)

def delete_task(request, pk):

    task = Task.objects.get(id=pk)

    if request.method == 'POST':
        task.delete()

        return redirect('index')

    context = {
        'task': task,
    }

    return render(request, 'delete_task.html', context)

app/templates/create_task.html
{% extends 'main.html' %}

{% block content %}
<div class="row">
    <div class="col m-5">
        <h3 class="mb-4">New Task</h3>
        <a href="{% url 'index' %}"><button class="btn btn-primary mb-4">Previous</button></a>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-success" type="submit" value="Salvar">
        </form>
    </div>
</div>

{% endblock %}

{% block scripts %}

<script>
    $(document).ready(function () {
        $("#id_title").addClass("form-control");
        $("#id_description").addClass("form-control");
    });
</script>

{% endblock %}

app/templates/delete_task.html
{% extends 'main.html' %}

{% block content %}
<div class="row">
    <div class="col m-5">
        <h3 class="mb-4">Delete Task</h3>
        
        <h5 class="mb-4">Are you sure you want to complete {{ task.title }}?</h5>
        
        <form class="mb-4" action="" method="post">
            {% csrf_token %}
            <input class="btn btn-success" type="submit" value="Complete">
        </form>
        <a href="{% url 'index' %}">
            <button class="btn btn-primary">Cancel</button>
        </a>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'main.html' %}

{% block content %}
<div class="row">
    <div class="col m-5">
        <h3 class="mb-4">Tasks</h3>
        <a href="{% url 'create_task' %}"><button class="btn btn-primary mb-4">+ New Task</button></a>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th scope="col">Task</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                <tr>
                    <td>{{ task.title }}</td>
                    <td>
                        <a class="btn btn-warning" href="{% url 'update_task' task.pk %}">
                            Update
                        </a>
                        <a class="btn btn-success" href="{% url 'delete_task' task.pk %}">
                            Complete
                        </a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>
        </table>
    </div>
</div>
{% endblock %}

app/templates/update_task.html
{% extends 'main.html' %}

{% block content %}
<div class="row">
    <div class="col m-5">
        <h3 class="mb-4">Update Task</h3>
        <a href="{% url 'index' %}"><button class="btn btn-primary mb-4">Previous</button></a>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-success" type="submit" value="Salvar">
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}

<script>
    $(document).ready(function () {
        $("#id_title").addClass("form-control");
        $("#id_description").addClass("form-control");
    });
</script>

{% endblock %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>&middot; Tasks</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
    {% block content %}
        
    {% endblock %}


    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    
    {% block scripts %}

    {% endblock %}

</body>
</html>